# A workflow to publish a Maven package to GitHub Packages
name: Publish package to GitHub Packages

on:
  release:
    types: [created] # Run only when a new release is created

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Grant permission to write packages

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Publish to GitHub Packages
        # The GITHUB_TOKEN is automatically created by Actions
        # It's used for authentication with the GitHub Packages registry
        run: mvn -B deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
